### ISSUE TITLE
裝了本地搜尋插件後，hexo g 會報錯

### ISSUE THREAD

**Issue by changchichung** [chaooo/hexo-theme-BlueLake#31]
安裝 2.2.0版本
npm install hexo-generator-json-content@2.2.0 --save 

```
> hexo-util@0.6.0 postinstall /usr/share/nginx/html/hexoblog/node_modules/hexo-generator-json-content/node_modules/hexo-util
> npm run build:highlight

> hexo-util@0.6.0 build:highlight /usr/share/nginx/html/hexoblog/node_modules/hexo-generator-json-content/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

hexo-generator-json-content@2.2.0 node_modules/hexo-generator-json-content
├── keyword-extractor@0.0.14 (underscore@1.7.0, underscore.string@2.3.3)
└── hexo-util@0.6.0 (striptags@2.2.1, html-entities@1.2.1, cross-spawn@4.0.2, camel-case@3.0.0, bluebird@3.5.0, highlight.js@9.12.0)
```

裝完之後，執行 hexo g 會報錯
```
[root@3cx1 hexoblog]# hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Object  has no method 'find'
    at site.posts.sort.filter.filter.map.actualPost (/usr/share/nginx/html/hexoblog/node_modules/hexo-generator-json-content/index.js:126:20)
    at Query.filter (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/warehouse/lib/query.js:305:9)
    at Hexo.hexo_generator_json_content (/usr/share/nginx/html/hexoblog/node_modules/hexo-generator-json-content/index.js:124:7)
    at Hexo.tryCatcher (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /usr/share/nginx/html/hexoblog/node_modules/hexo/lib/hexo/index.js:340:24
    at tryCatcher (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init [as _init$] (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/usr/share/nginx/html/hexoblog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:458:13)
```

請問該怎麼解決？

**Comment by chaooo** [comment]
看是不是node的版本和hexo版本与[hexo-generator-json-content](https://github.com/alexbruno/hexo-generator-json-content)版本不匹配
