### ISSUE TITLE
不支持<!--more--> 添加后hexo g 会报错

### ISSUE THREAD

**Issue by zhangyongbo** [chaooo/hexo-theme-BlueLake#33]
不支持 添加后hexo g 会报错
```sh
hexo g 
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Language must be one of [danish,dutch,english,french,galician,german,italian,polish,portuguese,russian,spanish,swedish]
    at Object._extract [as extract] (/Users/ZYB/Hexo/node_modules/keyword-extractor/lib/keyword_extractor.js:24:15)
    at getKeywords (/Users/ZYB/Hexo/node_modules/hexo-generator-json-content/index.js:58:19)
    at setContent (/Users/ZYB/Hexo/node_modules/hexo-generator-json-content/index.js:77:21)
    at postsNames.reduce (/Users/ZYB/Hexo/node_modules/hexo-generator-json-content/index.js:125:52)
    at Array.reduce (native)
    at site.posts.sort.filter.map.post (/Users/ZYB/Hexo/node_modules/hexo-generator-json-content/index.js:125:30)
    at Model._Query.Query.Query.map (/Users/ZYB/Hexo/node_modules/warehouse/lib/query.js:229:17)
    at Hexo.hexo.extend.generator.register.site (/Users/ZYB/Hexo/node_modules/hexo-generator-json-content/index.js:125:7)
    at Hexo.tryCatcher (/Users/ZYB/Hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/ZYB/Hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/ZYB/Hexo/node_modules/hexo/lib/hexo/index.js:340:24
    at tryCatcher (/Users/ZYB/Hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/ZYB/Hexo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/ZYB/Hexo/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/ZYB/Hexo/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/Users/ZYB/Hexo/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/Users/ZYB/Hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/ZYB/Hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ZYB/Hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

```
![](http://ogeomshjx.bkt.clouddn.com//Fu6rdYQTagK0Vch0YQVWJwDdfJKv)

**Comment by chaooo** [comment]
应该写在新的一行吧，也可在文章头信息中添加 description 字段填写自定义的文章简述。
