### ISSUE TITLE
RSS订阅与搜索框插件下载的安装错误

### ISSUE THREAD

**Issue by xiaomizhou66** [chaooo/hexo-theme-BlueLake#65]
λ hexo server
ERROR Plugin load failed: hexo-generator-sitemap
Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\qianduan_dir\mybolg\node_modules\brace-expansion\index.js:1:79)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\qianduan_dir\mybolg\node_modules\_minimatch@3.0.4@minimatch\minimatch.js:10:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\qianduan_dir\mybolg\node_modules\_hexo-generator-sitemap@1.2.0@hexo-generator-sitemap\lib\generator.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (F:\qianduan_dir\mybolg\node_modules\hexo\lib\hexo\index.js:219:21)
ERROR Plugin load failed: hexo-renderer-jade
Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\qianduan_dir\mybolg\node_modules\_hexo-renderer-jade@0.3.0@hexo-renderer-jade\lib\renderer.js:3:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (F:\qianduan_dir\mybolg\node_modules\hexo\lib\hexo\index.js:219:21)
    at F:\qianduan_dir\mybolg\node_modules\hexo-renderer-jade\index.js:4:47
    at fs.readFile.then.script (F:\qianduan_dir\mybolg\node_modules\hexo\lib\hexo\index.js:232:12)
    at tryCatcher (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\promise.js:638:18)
    at F:\qianduan_dir\mybolg\node_modules\bluebird\js\release\nodeback.js:42:21
    at F:\qianduan_dir\mybolg\node_modules\graceful-fs\graceful-fs.js:78:16
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.

**Comment by xiaomizhou66** [comment]
请问这个怎么解决，谢谢~

**Comment by chaooo** [comment]
去hexo-generator-sitemap的github仓库看看
